

export const emails = [
  {
    id: 1,
    category: "primary",
    sender: "Jane Doe",
    subject: "Tickets for tonight",
    date: "June 20 Friday",
    description:
      "I was finally able to get the tickets! We'll meet up at the main bustop.",
    },
  {
    id: 2,
    category: "primary",
    sender: "Mom",
    subject: "Weekend plans",
    date: "June 13 Friday",
    description: "Are you free for dinner this weekend? Let me know if you are.",
  },
  {
    id: 3,
    category: "primary",
    sender: "Dad",
    subject: "Weekend plans",
    date: "June 13 Friday",
    description: "Did your mom already tell about dinner this weekend?",
  },
  {
    id: 4,
    category: "transactions",
    sender: "InBank",
    subject: "Payment recieved",
    date: "June 7 Saturday",
    description: "You have recieved a payment from Tech Agency. Log in to InBank to view more details",
  },
  {
    id: 5,
    category: "transactions",
    sender: "Amazon",
    subject: "Your order has shipped",
    date: "May 7 Wednesday",
    description: "Your package is on its way. Track your order here.",
  },
  {
    id: 6,
    category: "transactions",
    sender: "Nike",
    subject: "Order confirmation",
    date: "May 7 Wednesday",
    description: "Your order was placed successfully, Thank you for your order, details are below.",
  },
  {
    id: 7,
    category: "updates",
    sender: "Slack",
    subject: "Workspace downtime notice",
    date: "May 17 Saturday",
    description: "We'll be performing maintenance tonight at 11 PM.",
  },
  {
    id: 8,
    category: "updates",
    sender: "MessageMe",
    subject: "New updates available",
    date: "May 12 Monday",
    description: "You can access the new features in your settings features section.",
  },
  {
    id: 9,
    category: "updates",
    sender: "LinkedIn",
    subject: "New connection request",
    date: "March 13 Thursday",
    description: "You have a new connection request from Sarah.",
  },
  {
    id: 10,
    category: "business",
    sender: "John Smith",
    subject: "Meeting reschedule",
    date: "June 17 Tuesday",
    description:
      "Can we push our meeting to 3 PM instead? Let me know if that works for you.",
  },
  {
    id: 11,
    category: "business",
    sender: "Tech Agency",
    subject: "Design revamp",
    date: "June 12 Thursday",
    description: "The remaining files will be sent to you tommorrow, other details as well.",
  },
  {
    id: 12,
    category: "business",
    sender: "EstateGroup",
    subject: "Website build",
    date: "June 9 Monday",
    description: " Hi John I need a multipage full scale real estate website.",
  },
];

